apiVersion: v1
kind: PersistentVolume
metadata:
  name: glusterfs-influxdb 
spec:
  capacity:
      storage: "199Gi"
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs
    path: gluster
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
